### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by koojunho** [ModernPUG/iamport-rest-client-modern-php#1]
@tael 님 코드 개선 감사합니다. 코드 접근이 한층 더 편한 세팅이 되셨을거라 판단되는데요.
이 프로젝트 설계에 관하여 말씀해주셨던 몇 가지 아이디어를 적용해보면 어떨까 싶습니다.

그 후 정의된 설계를 구현하면 1.0.x 로 태깅하기로 하면 어떨까요?
API 수정이 필요해보이는데 버전 합의 없이 고쳐도 될지 의문이기 때문입니다.
그 후 안정화된 버전에 대해서 1.0.\* 로 가져가기를 권장하는 설명이 필요할듯 싶고요.
- [ ] API 네이밍 및 인터페이스 합의
  - 현재 iamport 의 코드 내에서도 CamelCase 와 snake_case 동시에 제공되는듯 합니다. 이를 맞추면서 해당 메소드가 어떤 기능을하는지 명확하게 알 수 있는 이름이 필요할듯 싶고요.
  - Arguments 를 어떻게 받을지도 고민이 필요합니다.
- [x] Guzzle 적용
- [ ] [Iamport 방식](https://github.com/ModernPUG/iamport-rest-client-modern-php/blob/5be43ad64acd964df2e8ac188c36ce9a52f6ab28/src/Iamport.php#L40)의 결과 Object 화 진행 여부.
  - 현재 list 로 받아야 하는 결과에 대해서는 Iamport 코드에서 별도 result 용 클래스를 구현하지 않고 있는듯 합니다. 이를 연관배열로 받을지, Object 로 래핑할 지 여부 같은 것입니다.
- [x] 테스트
- [ ] AWS 식 구조 (앞선 테스크에서 interface 만 맞추고 이 테스크는 1.0 이후에 수정하는 게 나을지도)
- [x] 옵셔널하게 선택 가능한 Laravel 편의 기능 (Laravel 사용 안하면 안써도 됨)

의견 남겨주세요~

**Comment by tael** [comment]
최종 결과는 다르겠지만 제생각만 정리해볼게요.

**API 네이밍 및 인터페이스 합의**
- 메소드 = CamelCase
- 프로퍼티 = CamelCase + snake_case (기본으로 공식 문서상 snake_case 를 통해 표현하기 때문에 허용하되 CamelCase 접근방식을 가능토록 함, 방식은 찾아봐야겠죠?)

**Guzzle 적용**
- 이건 금방 될듯. 그냥 curl을 걷어내고 guzzle을 쓰면 되겠네요. 

**Iamport 방식의 결과 Object 화 진행 여부**
- 오브젝트 래핑을 생각하고 있습니다. 
- 개인취향은 오브젝트만 받고 싶지만, 범용성을 위해 연관배열(array)를 동시에 지원하는 방향을 생각해 봐야겠습니다. 구현이 쉬운건 연관배열이니 우선하고, 향후 오브젝트를 추가하는 것은 어떨지 고민해봅니다. (손이 많이가고 예외사항이 있을듯?)

```
/**
* @param XXXRequestData|array
**/
public function getXXX($requestData){}
```

**테스트**
- 서비스에서 제공되는 REST 자체에서도 테스트가 어려웠습니다. 유닛테스트가 쉽진 않겠지만 물어물어 방법을 찾아볼 생각입니다.

**AWS 식 구조**
-  (앞선 테스크에서 interface 만 맞추고 이 테스크는 1.0 이후에 수정하는 게 나을지도) -> 동의합니다.

**Comment by tael** [comment]
**테스트 외에 샘플제작이 필요합니다.**
제 환경에서도 그렇고 유닛테스트가 있다 한들, 샘플이 없으면 쓸줄 모르는 분들도 있습니다.
현실적으로 유닛테스트와 별개의 샘플+테스트가 진행될 수 있어야 할것 같다는 생각입니다.

**태깅 관련**
아는게 없어 배우고 따라가겠습니다.

**interface 구현?**
구현시 강제 제약을 위해 인터페이스를 별도 구현하는 것을 고민하고있습니다. 말그대로 고민입니다.
실무에서 저는 인터페이스를 활용하고 있진 않습니다.

**Comment by koojunho** [comment]
발전이 있는 진행 정말 좋네요. 전부 동의하고요.

**Iamport 방식의 결과 Object 화 진행 여부**
에서 파라메터 말고 리턴타입도 고려해주세요. 이것은 1.0 스팩 내에서 해결돼야 할듯요. Update 했더니 연관배열이 아니고 Object 가 리턴되면 저희 사이트 망할 수 있으니까요. ㅋㅋ 리스트 타입 오브젝트 래핑은 이터레이션을 두 번 해야되고(래핑 할 때와, 클라이언트 개발자 응용에서 가져갈 때) Iamport API가 버전 업 될때마다 신경을 써야돼서 싫어하긴 하는데 저 혼자 쓰는게 아닌 경우라 tael님 팀 결정을 따르겠습니다.

**샘플, 태깅**
몇 번 말씀나눈 path 방식으로, 개발 중인 패키지 import 하는 샘플 프로젝트 별도로 만들겠습니다. 여기서 태그 달아 배포하기 등을 구성 or 설명 해놓겠습니다.

**interface**
어떻게 해야할지 잘 모르겠습니다. 구현하려는 API 가 두 개면 공통분모를 뽑으면 될텐데 미리 구성했는데 잘못하면 구현과 함께 계속 같이 변하면서 강제로 제약도하며 괴롭히지 않을까 걱정입니다. YAGNI 로 가시죠.

**Comment by tael** [comment]
**ResultObject**
리턴은 여러가지가 아니죠 참.
개취는... 옵션을 여럿 두는 취향은 아니지만, ArrayAccessble (?) 을 통해 해결할 수도 있습니다.
일단 알겠습니다.

**샘플**
중간에 커밋이 더러워지는건 별로이지만 단순한 샘플페이지를 만들고 있습니다. (방금 샘플 프로젝트가 생성된걸 확인했습니다만...)
이건 국내 서비스 사이트에서 php 연동을 위해 쓰는 아주 레거시한 스타일인데, 어느정도는 필요할 것 같아서요.
나중에 지워야한다고 생각하지만, 샘플프로젝트랑 별개로 아주 짧은 이터레이션동안 유지하려 합니다. (조금 참아주세요ㅠㅠ)

**인터페이스**
YAGNI 동의합니다. 차후에 고려하시죠. 머리아프네요.

**Comment by koojunho** [comment]
샘플 프로젝트는 뭔가 좀 이상하다 했는데 vendor 를 커밋하는 바람에 지우고 셀프 반성 중입니다.
말씀하신 샘플은 별도로 관리하신다는 거죠? 저는 상관 없습니다.

**Comment by tael** [comment]
네 심플한 sample.php 같은걸 제공하는건데 
뭐 제공한다 라는 느낌보단 사실 환경 갖춰지기 전에 테스트 목적이 크죠.

**Comment by koojunho** [comment]
몇 가지 좋은 거 알게된 것이 있는데요. 일전에 PHPStorm 에서 git in git 제가 원하는 기능 잠깐 살아났다가 사라졌다고 당황한 거 말씀드린 것 있잖아요. 그거 sample 만드는 김에 확인해봤는데 인텔리제이 우상단에 뜨는 팝업에서 detected 된 sub git repo 를 add root 하겠다고 클릭하니까 각각 자기 repo 로 넣도록 알아서 잘 작동하네요.

![서브 repo 가 남다르게 표현되고 있는 모습](https://cloud.githubusercontent.com/assets/334933/13312122/7bf36c02-dbd7-11e5-904a-6f43d3c44aa5.png)
위 이미지는 github 내에서도 서브 repo 가 남다르게 표현되고 있는 모습을 캡쳐한 것입니다.

sample 프로젝트의 [readme](https://github.com/ModernPUG/iamport-rest-client-sample/blob/master/readme.md) 보고 세팅 하시면 ide 에서 위의 기능이 그대로 살아날 것으로 예상되고요.

laravel 설정만 하시면 바로 아래 메세지 보실 수 있을 것 같아요.

```
ModernPUG\Iamport\IamportResult Object ( [success] => [data] => [error] => Array ( [code] => -1 [message] => [API인증오류] 인증에 실패하였습니다. API키와 secret을 확인하세요. ) )
```

sample 에 대한 경험도 오픈되어 공유되면 좋다고 생각하는데 세팅 함 해보세요. 정말 편합니다. '패키지를 여기서 이 목적으로 이렇게 호출하는데 뭐가 어때서 불편해요.. 봐주세요~' <-- 이런 대화도 가능할 것 같고요.

더불어 아이디어가 생겼는데요. 패키지를 지금처럼 plain 하게 사용하는 방법도 있겠지만 laravel service provider 하나 제공하면 좋겠네요. 같이 제공하고 laravel 안쓰면 말고 형태의 패키지요. 아실듯. 요 작업 먼저 하고 있겠습니다.

**Comment by tael** [comment]
와 뭔가 어렵네요. 분명 같이 이야기 했던 건데..ㅋㅋ

git in git 은 컴포저 파일경로로 리포 설정하는걸 이제 안해도 된다는 이야기 같은데요.
샘플도 살펴보고 나중에 세팅해서 한번 해봐야겠네요.

서비스프로바이더는 별도 프로젝트로 보통 하지 않던가요? 잘 모르겠어요. 프로바이더 쓰던가, 쌩으로 쓰던가. 의 옵션을 한 프로젝트에서 줄 수 있는지. 가능하다면 상관없으니 진행하고요.
단점이 있다면 두가지 가이드라인을 readme에 넣어줘야해서 혼란스러울 수 있다는점.
이 옵션이 개발에 방해가 되는 것이 아니면 상관없을듯합니다. 고고싱

**Comment by koojunho** [comment]
https://github.com/maknz/slack 같은 경우가 `composer require maknz/slack` 까지만 하고 그냥 쓰던가, ServiceProvider 꽂아서 env, config, facade 도움 받아 편히 쓰던가를 제공하고 있고요. 그러고보니 readme 혼란이 있군요. 우선 합체 개발 후 아니다 싶으면 두개로 분리하겠습니다. 미리 나누면 복잡복잡.

**Comment by tael** [comment]
얍얍. 케이스가 있군요.
고민안해도 되겠습니다.

**Comment by koojunho** [comment]
내용 공유 됐고 개별 tasks 다른 이슈로 등록하겠습니다. 천천히 하셔요~
