### ISSUE TITLE
IamportResult 클래스 사용 방식 변경

### ISSUE THREAD

**Issue by tael** [ModernPUG/iamport-rest-client-modern-php#10]
IamportResult 클래스는 

```
    public $success = false;
    public $data;
    public $error;
```

에 값을 세팅하고 그 내용을 사용합니다.

에러가 있으면 throw exception 하면 될일이고, exception 안났으면 $success=true 일 일인데 왜 바로 $data를 안주는 지 모르겠습니다.
Result는 데이터 오브젝트로 사용하고, 성패를 결정하고 판단하는 것은 exception 을 적극 활용하도록 변경해야 합니다.

**Comment by koojunho** [comment]
이슈 https://github.com/ModernPUG/iamport-rest-client-modern-php/issues/5 와 어느정도 함께 가야하는 이슈군요~ 좋은 쪽으로 작성해주시고 정립되면 따라가겠습니다.

**Comment by koojunho** [comment]
@tael 님, promise 를 사용하고 응용측 then 안에서 알아서 가져다 쓰게 하는 방법 어떨까요? 데이터 파싱도 좋고 에러 핸들링에도 좋고요. 사용자가 이상하다고 할까봐 고민 중이긴 한데..

**Comment by koojunho** [comment]
``` PHP
public function getPaymentList()
{
    $paymentList = $this->iamport->getPaymentListAsync()
        ->then(function ($response) {
            $contents = $response->getBody()->getContents();
            $result = json_decode(trim($contents));
            return $result;
        })->then(null, function ($exception) {

        })->wait();

    return view('pages.paymentList', ['paymentList' => $paymentList->response->list]);
}
```

Async 코드로 만들어봤으나 사용자가 알아야 하는 게 너무 많아 보임.

``` PHP
public function getPaymentList()
{
    $paymentList = $this->iamport->getPaymentListAsync()
        ->then(function ($response) {
            return $response->getXXXX();
        })->then(null, function ($exception) {

        })->wait();

    return view('pages.paymentList', ['paymentList' => $paymentList->response->list]);
}
```

우선 middleware를 사용하여 위처럼 우리 비지니스에 맞는 response 로 바꿔 넣을 수 있는지 궁금함.

**Comment by koojunho** [comment]
- http://stackoverflow.com/questions/30530172/guzzle-6-no-more-json-method-for-responses
- https://blog.jacobemerick.com/web-development/json-responses-in-guzzle-six/

**Comment by tael** [comment]
Result 클래스가 완전히 사라져서 이슈 종결. 다시 살리게 될 일이 있을지 모르겠음.
