### ISSUE TITLE
getPaymentList() 삭제.

### ISSUE THREAD

**Issue by tael** [ModernPUG/iamport-rest-client-modern-php#13]
deprecated 되었고, getPaymentPage를 사용하도록 한다.
적절한 시점에 deprecated 된 getPaymentList를 삭제한다.

**Comment by tael** [comment]
@koojunho 님이 확인/수정 후에 삭제 커밋 날려주심 될듯요.

**Comment by koojunho** [comment]
우선 변경해주신 이후에 getPaymentList() 보다 response 쪽이 변경되어 샘플이 깨지기 시작했는데요.
변경하신 방법에 맞출까 하다가 네이밍이나 호출방식에서 다른 방법을 사용하려고 정했고요.
구현중인 라라벨쪽 캐시 지원 쪽을 강화해보고자 포크를 해볼까 합니다.
따라서 제 진행은 상관없이 변경하셔도 상관없어요~

**Comment by tael** [comment]
삭제 안된상태라 reopen
